### ISSUE TITLE
OnsenUI with emberjs

### ISSUE THREAD

**Issue by kirantpatil** [frankdiox/OnsenUI-Material-Tabbar#1]
Hi @frankdiox 

I would like to see an app with onsenui and ember.

Please point me to the app if you have hosted one or if someone is using.

Thanks.

**Comment by frandiox** [comment]
@kirantpatil Hello!

I'm sorry but I have never tried Ember.js with or without Onsen UI. Probably it will play nicely since Onsen 2 is framework agnostic but I cannot provide any sort of example right now :/

**Comment by kirantpatil** [comment]
@frankdiox, Thanks for your quick reply. I am asking this question where ever :smile:  I seen OnsenUI discussion platform.

So please consider it as one of high priority task so that at least people will come to know that ember is also supported.

Just one example will take OnsenUI to some distance to attract more users to try and evaluate.

Thanks alot.

**Comment by frandiox** [comment]
There are already many priority tasks before this one. For example, release the final version of Onsen UI 2.0 and proper documentation. After all of that is finished, if I have time I could check out Ember.js and see how it works. Right now I have no idea about it :sweat_smile:

**Comment by kirantpatil** [comment]
Great thanks for your support.

**Comment by kirantpatil** [comment]
Finally I could make it work in ember as below.
1. Install ember-cli 2.4.x
2. Create new project, "ember new emberonsen"
3. $ cd emberonsen
4. vi bower.json and add below line to dependenices section
   "onsenui": "2.0.0-beta.9"
5. $ bower install <= this command will install onsenui under bower_components directory
6. We need to import external js and css to ember by mentioning each file at ember-cli-build.js file as below.

```
app.import('bower_components/onsenui/css/onsen-css-components.css');
  app.import('bower_components/onsenui/css/onsen-css-components-blue-basic-theme.css');
  app.import('bower_components/onsenui/css/onsen-css-components-blue-theme.css');
  app.import('bower_components/onsenui/css/onsen-css-components-dark-theme.css');
  app.import('bower_components/onsenui/css/onsen-css-components-default.css');
  app.import('bower_components/onsenui/css/onsen-css-components-purple-theme.css');
  app.import('bower_components/onsenui/css/onsen-css-components-sunshine-theme.css');
  app.import('bower_components/onsenui/css/material-design-iconic-font/css/material-design-iconic-font.css');
  app.import('bower_components/onsenui/css/ionicons/css/ionicons.css');
  app.import('bower_components/onsenui/css/font_awesome/css/font-awesome.css');
  app.import('bower_components/onsenui/css/material-design-iconic-font/fonts/Material-Design-Iconic-Font.eot');
  app.import('bower_components/onsenui/css/material-design-iconic-font/fonts/Material-Design-Iconic-Font.svg');
  app.import('bower_components/onsenui/css/material-design-iconic-font/fonts/Material-Design-Iconic-Font.ttf');
  app.import('bower_components/onsenui/css/material-design-iconic-font/fonts/Material-Design-Iconic-Font.woff');
  app.import('bower_components/onsenui/css/material-design-iconic-font/fonts/Material-Design-Iconic-Font.woff2');
  app.import('bower_components/onsenui/css/ionicons/fonts/ionicons.eot');
  app.import('bower_components/onsenui/css/ionicons/fonts/ionicons.svg');
  app.import('bower_components/onsenui/css/ionicons/fonts/ionicons.ttf');
  app.import('bower_components/onsenui/css/ionicons/fonts/ionicons.woff');
  app.import('bower_components/onsenui/css/font_awesome/fonts/FontAwesome.otf');
  app.import('bower_components/onsenui/css/font_awesome/fonts/fontawesome-webfont.eot');
  app.import('bower_components/onsenui/css/font_awesome/fonts/fontawesome-webfont.svg');
  app.import('bower_components/onsenui/css/font_awesome/fonts/fontawesome-webfont.ttf');
  app.import('bower_components/onsenui/css/font_awesome/fonts/fontawesome-webfont.woff');
  app.import('bower_components/onsenui/css/font_awesome/fonts/fontawesome-webfont.woff2');
  app.import('bower_components/onsenui/css/onsenui.css');
  app.import('bower_components/onsenui/js/onsenui.js');

  return app.toTree();
};
```
1. Now add onsen components to app/templates/application.hbs file as below 

```
<ons-navigator title="Navigator" var="myNavigator">
  <ons-page>
<ons-button modifier="large--cta">
  Tap Me
</ons-button>
    <ons-toolbar>
      <div class="center">Basic List</div>
    </ons-toolbar>
    <ons-scroller>
      <ons-list>
        <ons-list-header>Numbers</ons-list-header>
        <ons-list-item>One</ons-list-item>
        <ons-list-item>Two</ons-list-item>
        <ons-list-item>Three</ons-list-item>
        <ons-list-item>Four</ons-list-item>
        <ons-list-item>Five</ons-list-item>
        <ons-list-item>Six</ons-list-item>

        <ons-list-header>Tappable Numbers</ons-list-header>
        <ons-list-item modifier="tappable">Tap Me</ons-list-item>
        <ons-list-item modifier="tappable">Tap Me</ons-list-item>
        <ons-list-item modifier="tappable">Tap Me</ons-list-item>
        <ons-list-item modifier="tappable">Tap Me</ons-list-item>
        <ons-list-item modifier="tappable">Tap Me</ons-list-item>
        <ons-list-item modifier="tappable">Tap Me</ons-list-item>
      </ons-list>
    </ons-scroller>
  </ons-page>
</ons-navigator>

```
1. $ ember s
2. Open browser with URL: localhost:4200 , now browser displays the onsen components mentioned application.hbs file

**Comment by kirantpatil** [comment]
Thanks @frankdiox for all your help. You guys have done Great job.

**Comment by kirantpatil** [comment]
Please find the screenshot here
![screenshot from 2016-04-15 16-56-14](https://cloud.githubusercontent.com/assets/1178055/14560108/1eece058-032b-11e6-8c01-a049b01b918d.png)

**Comment by frandiox** [comment]
@kirantpatil Thanks for sharing! If you have some code example on Github please share a link as well. We could mention it on the forum or the blog :)

**Comment by kirantpatil** [comment]
@frankdiox, please find the app link here, https://github.com/kirantpatil/onsenember.
