### ISSUE TITLE
OnsenUI with Rails

### ISSUE THREAD

**Issue by kirantpatil** [frankdiox/OnsenUI-Material-Tabbar#2]
Please provide sample example with Rails as well.

**Comment by frandiox** [comment]
@kirantpatil I'm sorry but I don't understand what's the relation between Onsen UI and Rails. Rails is a framework for the backend and OnsenUI is for the user interface in the frontend. Onsen UI is completely independent of what you use in the backend so I think there is nothing to show in an example here.

**Comment by kirantpatil** [comment]
Sure Sir, I agree with you, but let it open so that people can share if they have one. We are planning to use it with rails and will share the github link here.

Thanks.

**Comment by kirantpatil** [comment]
The steps have been mentioned in issue https://github.com/OnsenUI/OnsenUI/issues/1336, so closing this issue.
