### ISSUE TITLE
Angular js dependency issue

### ISSUE THREAD

**Issue by kirantpatil** [frankdiox/OnsenUI-Material-Tabbar#3]
Hello,

In the index.html page it contains below script file. If I remove them and save and refresh the webpage it does not work.

<script src="lib/onsen/js/angular/angular.min.js"></script>

<script src="lib/onsen/js/angular-onsenui.min.js"></script>

Why does it depend on angular ?

Can't we use the example app without angular ?

Please find the Screenshot when above angular js scripts are removed.

![screenshot from 2016-03-31 18-09-52](https://cloud.githubusercontent.com/assets/1178055/14175990/4fa3d758-f76c-11e5-9b59-c341e37ab5a8.png)

Thanks.

**Comment by frandiox** [comment]
There are two versions of this application. Master branch is implemented with AngularJS, what means it obviously needs Angular as a dependency. If you want to see a version without Angular, check the [js-implementation](https://github.com/frankdiox/OnsenUI-Material-Tabbar/tree/js-implementation) branch.

**Comment by kirantpatil** [comment]
ok thanks.
